POST http://localhost:1323/api/manager/user?email=max@mail.com&password=123123
Accept: application/json
Content-Type: application/json

###

POST http://localhost:1323/api/auth?email=max@mail.com&password=123123
Accept: application/json
Content-Type: application/json

###
GET http://localhost:1323/api/user/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJc3N1ZXIiOiJsb2NhbC1jaGFpbiIsImFkbWluIjp0cnVlLCJleHAiOjE2NTEzNDE1ODMsImlkIjoiOCIsIm5hbWUiOiJtYXhAbWFpbC5jb20ifQ.qVtMzCfyIyrOkZtBtrDUBXcKbEQI_aso2NsveUMoy2o

