create table account (
    id            int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status         smallserial
        CONSTRAINT state_check CHECK (status > 0 and status <= 15),
    phone         varchar(255) NOT NULL,
    dob           date         NOT NULL,
    user_id       int          NOT NULL,
    created_at    timestamp    NOT NULL,
    updated_at    timestamp    NOT NULL,
    updated_by    int          NOT NULL,
    created_by    int          NOT NULL
);