create table wallet (
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status      smallserial
        CONSTRAINT state_check CHECK (status > 0 and status <= 15),
    wallet_id   varchar(512) NOT NULL,
    private_key varchar(512) NOT NULL,
    created_at  timestamp    NOT NULL,
    updated_at  timestamp    NOT NULL,
    created_by  int          NOT NULL,
    updated_by  int          NOT NULL,
    account_id  int          NOT NULL
);