// Code generated by MockGen. DO NOT EDIT.
// Source: transactor.go

// Package service_test is a generated GoMock package.
package service_test

import (
	inMem "local-chain/internal/adapters/outbound/inMem"
	leveldb "local-chain/internal/adapters/outbound/leveldb"
	types "local-chain/internal/types"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// BlockTransactions mocks base method.
func (m *MockStore) BlockTransactions() *leveldb.BlockTransactionsStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockTransactions")
	ret0, _ := ret[0].(*leveldb.BlockTransactionsStore)
	return ret0
}

// BlockTransactions indicates an expected call of BlockTransactions.
func (mr *MockStoreMockRecorder) BlockTransactions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockTransactions", reflect.TypeOf((*MockStore)(nil).BlockTransactions))
}

// Blockchain mocks base method.
func (m *MockStore) Blockchain() *leveldb.BlockchainStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Blockchain")
	ret0, _ := ret[0].(*leveldb.BlockchainStore)
	return ret0
}

// Blockchain indicates an expected call of Blockchain.
func (mr *MockStoreMockRecorder) Blockchain() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Blockchain", reflect.TypeOf((*MockStore)(nil).Blockchain))
}

// Transaction mocks base method.
func (m *MockStore) Transaction() *leveldb.TransactionStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transaction")
	ret0, _ := ret[0].(*leveldb.TransactionStore)
	return ret0
}

// Transaction indicates an expected call of Transaction.
func (mr *MockStoreMockRecorder) Transaction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockStore)(nil).Transaction))
}

// User mocks base method.
func (m *MockStore) User() *leveldb.UserStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User")
	ret0, _ := ret[0].(*leveldb.UserStore)
	return ret0
}

// User indicates an expected call of User.
func (mr *MockStoreMockRecorder) User() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockStore)(nil).User))
}

// Utxo mocks base method.
func (m *MockStore) Utxo() *leveldb.UtxoStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Utxo")
	ret0, _ := ret[0].(*leveldb.UtxoStore)
	return ret0
}

// Utxo indicates an expected call of Utxo.
func (mr *MockStoreMockRecorder) Utxo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Utxo", reflect.TypeOf((*MockStore)(nil).Utxo))
}

// MockTransactionStore is a mock of TransactionStore interface.
type MockTransactionStore struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionStoreMockRecorder
}

// MockTransactionStoreMockRecorder is the mock recorder for MockTransactionStore.
type MockTransactionStoreMockRecorder struct {
	mock *MockTransactionStore
}

// NewMockTransactionStore creates a new mock instance.
func NewMockTransactionStore(ctrl *gomock.Controller) *MockTransactionStore {
	mock := &MockTransactionStore{ctrl: ctrl}
	mock.recorder = &MockTransactionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionStore) EXPECT() *MockTransactionStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockTransactionStore) Get(id uuid.UUID) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTransactionStoreMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTransactionStore)(nil).Get), id)
}

// Put mocks base method.
func (m *MockTransactionStore) Put(arg0 *types.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockTransactionStoreMockRecorder) Put(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockTransactionStore)(nil).Put), arg0)
}

// MockBlockTxStore is a mock of BlockTxStore interface.
type MockBlockTxStore struct {
	ctrl     *gomock.Controller
	recorder *MockBlockTxStoreMockRecorder
}

// MockBlockTxStoreMockRecorder is the mock recorder for MockBlockTxStore.
type MockBlockTxStoreMockRecorder struct {
	mock *MockBlockTxStore
}

// NewMockBlockTxStore creates a new mock instance.
func NewMockBlockTxStore(ctrl *gomock.Controller) *MockBlockTxStore {
	mock := &MockBlockTxStore{ctrl: ctrl}
	mock.recorder = &MockBlockTxStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockTxStore) EXPECT() *MockBlockTxStoreMockRecorder {
	return m.recorder
}

// GetByBlockTimestamp mocks base method.
func (m *MockBlockTxStore) GetByBlockTimestamp(t uint64) (types.Transactions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBlockTimestamp", t)
	ret0, _ := ret[0].(types.Transactions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBlockTimestamp indicates an expected call of GetByBlockTimestamp.
func (mr *MockBlockTxStoreMockRecorder) GetByBlockTimestamp(t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBlockTimestamp", reflect.TypeOf((*MockBlockTxStore)(nil).GetByBlockTimestamp), t)
}

// Put mocks base method.
func (m *MockBlockTxStore) Put(envelope *types.BlockTxsEnvelope) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", envelope)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockBlockTxStoreMockRecorder) Put(envelope interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockBlockTxStore)(nil).Put), envelope)
}

// MockUTXOStore is a mock of UTXOStore interface.
type MockUTXOStore struct {
	ctrl     *gomock.Controller
	recorder *MockUTXOStoreMockRecorder
}

// MockUTXOStoreMockRecorder is the mock recorder for MockUTXOStore.
type MockUTXOStoreMockRecorder struct {
	mock *MockUTXOStore
}

// NewMockUTXOStore creates a new mock instance.
func NewMockUTXOStore(ctrl *gomock.Controller) *MockUTXOStore {
	mock := &MockUTXOStore{ctrl: ctrl}
	mock.recorder = &MockUTXOStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUTXOStore) EXPECT() *MockUTXOStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockUTXOStore) Get(pubKey []byte) ([]*types.UTXO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", pubKey)
	ret0, _ := ret[0].([]*types.UTXO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUTXOStoreMockRecorder) Get(pubKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUTXOStore)(nil).Get), pubKey)
}

// Put mocks base method.
func (m *MockUTXOStore) Put(pubKey []byte, utxos ...*types.UTXO) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{pubKey}
	for _, a := range utxos {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Put", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockUTXOStoreMockRecorder) Put(pubKey interface{}, utxos ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{pubKey}, utxos...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockUTXOStore)(nil).Put), varargs...)
}

// MockTxPool is a mock of TxPool interface.
type MockTxPool struct {
	ctrl     *gomock.Controller
	recorder *MockTxPoolMockRecorder
}

// MockTxPoolMockRecorder is the mock recorder for MockTxPool.
type MockTxPoolMockRecorder struct {
	mock *MockTxPool
}

// NewMockTxPool creates a new mock instance.
func NewMockTxPool(ctrl *gomock.Controller) *MockTxPool {
	mock := &MockTxPool{ctrl: ctrl}
	mock.recorder = &MockTxPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxPool) EXPECT() *MockTxPoolMockRecorder {
	return m.recorder
}

// AddTx mocks base method.
func (m *MockTxPool) AddTx(tx *types.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTx", tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTx indicates an expected call of AddTx.
func (mr *MockTxPoolMockRecorder) AddTx(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTx", reflect.TypeOf((*MockTxPool)(nil).AddTx), tx)
}

// AddUtxos mocks base method.
func (m *MockTxPool) AddUtxos(pubKey []byte, utxos ...*types.UTXO) {
	m.ctrl.T.Helper()
	varargs := []interface{}{pubKey}
	for _, a := range utxos {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AddUtxos", varargs...)
}

// AddUtxos indicates an expected call of AddUtxos.
func (mr *MockTxPoolMockRecorder) AddUtxos(pubKey interface{}, utxos ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{pubKey}, utxos...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUtxos", reflect.TypeOf((*MockTxPool)(nil).AddUtxos), varargs...)
}

// GetPool mocks base method.
func (m *MockTxPool) GetPool() inMem.Pool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPool")
	ret0, _ := ret[0].(inMem.Pool)
	return ret0
}

// GetPool indicates an expected call of GetPool.
func (mr *MockTxPoolMockRecorder) GetPool() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPool", reflect.TypeOf((*MockTxPool)(nil).GetPool))
}

// GetUTXOs mocks base method.
func (m *MockTxPool) GetUTXOs(pubKey []byte) types.UTXOs {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUTXOs", pubKey)
	ret0, _ := ret[0].(types.UTXOs)
	return ret0
}

// GetUTXOs indicates an expected call of GetUTXOs.
func (mr *MockTxPoolMockRecorder) GetUTXOs(pubKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUTXOs", reflect.TypeOf((*MockTxPool)(nil).GetUTXOs), pubKey)
}

// Purge mocks base method.
func (m *MockTxPool) Purge() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Purge")
}

// Purge indicates an expected call of Purge.
func (mr *MockTxPoolMockRecorder) Purge() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Purge", reflect.TypeOf((*MockTxPool)(nil).Purge))
}
