name: Go

on:
  push:
    branches: [main, develop]
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build, Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Lint
        run: make lint
        working-directory: ./internal

#      skip until cmd is ready
#      - name: Build
#        run: go build -v
#        working-directory: ./internal

      - name: Test
        run: make test
        working-directory: ./internal
